### ISSUE TITLE
Tft Button blinking when stay pressed

### ISSUE THREAD

**Issue by Stephan35** [adafruit/Adafruit_TouchScreen#18]
Hello,

I solved a problem with my tft and adafruit gfx library.

When i stay pressed on button , it blinking.

here is lines i had to change to get it work without blinking.
`if (samples[0] - samples[1] < -4 || samples[0] - samples[1] > 4) {`
to
`if (samples[0] - samples[1] < -75 || samples[0] - samples[1] > 75) {`

Hope give some help.

**Comment by ladyada** [comment]
ok!
