### ISSUE TITLE
Need help to wire  XM, YM, XP, YP 

### ISSUE THREAD

**Issue by Mustafa-Montaser** [adafruit/Adafruit_TouchScreen#32]
Iam using 2.8 TFT touch screen with parallel interface
I don't know which pin should I choose for XM, YM, XP, YP .
TFT pins are LCD_D0 : LCD_D7 , LCD_RST , LCD_CS, LCD_WR and LCD_RD 
.
I use this screen with ESP32 DIVKIT V1.
My second question is which pin should I choose in ESP32 for connection to TFT

**Comment by caternuson** [comment]
Touch is done as a physical overlay on top of TFTs. Based on the pins you mention, it sounds like you have a non-touch TFT.

**Comment by ladyada** [comment]
@Mustafa-Montaser contact the place you bought hardware for tech support.
